name: Deploy to Github Page Repository(Google-DSC-Kookmin.github.io)

on:
  push:
    branches:
      - main  # TODO : Delete (For debug)
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  PULL_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_URL : ${{ github.event.pull_request.html_url }}

jobs:
  Deploy_to_other_repo:
    # if: contains(github.event.pull_request.labels.*.name, 'no update') == false && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
    
      - name : Build React Page
        run: |
          npm install
          npm rum build

      - name: Create New Branch and Commit Build Result
        run: |
          cd build
          git init
          git checkout -b React-Front_$(date +'%Y.%m.%d.%H.%M.%S')
          git add .
          git commit -m "Commit build result"

      - name: Push to B Repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          repository: Google-DSC-Kookmin/Google-DSC-Kookmin.github.io
          branch: React-Front_$(date +'%Y.%m.%d.%H.%M.%S')
          directory: build

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "React-Front_$(date +'%Y.%m.%d.%H.%M.%S')"
          destination_branch: "main"
          github_token: ${{ env.GITHUB_TOKEN }}
          pr_title: "New React build result - $(date +'%Y.%m.%d.%H.%M.%S')"
          pr_body: "This PR is auto-generated by Github Action. Source commit SHA: ${{ env.PULL_SHA }}. [Link to A Repo](${{ env.PULL_URL }})"
          pr_label: "auto"
